---
- name: include variables
  include_vars: ../vars/vars.yml

- name: Install required packcges
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items: {{ packets  }}
